In [1]:
pip install wikipedia


  Preparing metadata (setup.py) ... done
  Created wheel for wikipedia: filename=wikipedia-1.4.0-py3-none-any.whl size=11680 sha256=40165e7bd4d8a53d48b424f7265d35cad75d955363a3c953ddf58fedf716114d
  Stored in directory: /root/.cache/pip/wheels/5e/b6/c5/93f3dec388ae76edc830cb42901bb0232504dfc0df02fc50de
Successfully built wikipedia


In [2]:
import wikipedia

search_results = wikipedia.search("football")

search_results = search_results[:4]
doc_content = []

# Specify the maximum number of search results to consider
max_results = 3
# Specify the maximum number of characters to extract from each page
max_content_length = 4000

# Iterate over the search results
for title in search_results[:max_results]:
    page_object = wikipedia.page(title)
    con = page_object.content[:max_content_length]
    doc_content.append(con)

    # Extract and print the content of the current page
    print("Title:", page_object.title)
    print("Content:", con)
    print("\n---\n")

Title: Football
Content: Football is a family of team sports that involve, to varying degrees, kicking a ball to score a goal.  Unqualified, the word football normally means the form of football that is the most popular where the word is used. Sports commonly called football include association football (known as soccer in Australia, Canada, South Africa, the United States, and sometimes in Ireland and New Zealand); Australian rules football; Gaelic football; gridiron football (specifically American football, Arena football, or Canadian football); International rules football; rugby league football; and rugby union football. These various forms of football share, to varying degrees, common origins and are known as "football codes".
There are a number of references to traditional, ancient, or prehistoric ball games played in many different parts of the world. Contemporary codes of football can be traced back to the codification of these games at English public schools during the 19th ce

In [3]:
!pip install spacy
!python -m spacy download en_core_web_sm


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 11.7 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [4]:
import numpy as np
import pandas as pd
import os
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re
from gensim.models import FastText
import spacy
from nltk.corpus import stopwords
nltk.download('stopwords')
import tensorflow as tf
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense,SimpleRNN

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [5]:
stop_words = set(stopwords.words('english'))
def clean_text(sentence):
    # Removing URLS
    sentence = re.sub(r"https?://\S+|www\.\S+"," ",sentence)

    # Removing html tags
    sentence = re.sub(r"<.*?>|&([a-z0-9]+|#[0-9]{1,6}|#x[0-9a-f]{1,6});"," ",sentence)

    # Removing the Punctuation
    sentence = re.sub(r"[^\w\s]", " ", sentence)

    # Removing words that have numbers
    sentence = re.sub(r"\w*\d\w*", " ", sentence)

    # Removing Digits
    sentence = re.sub(r"[0-9]+", " ", sentence)

    # Cleaning white spaces
    sentence = re.sub(r"\s+", " ", sentence).strip()

    sentence = sentence.lower()
    # Check stop words
    tokens = []
    for token in sentence.split():
        if token not in stop_words:
            tokens.append(token)
    return " ".join(tokens)

In [6]:
# print(doc_content)
clean_doc=[]
for doc in doc_content:
  clean=clean_text(doc)
  clean_doc.append(clean)


In [7]:
print(clean_doc[0])

football family team sports involve varying degrees kicking ball score goal unqualified word football normally means form football popular word used sports commonly called football include association football known soccer australia canada south africa united states sometimes ireland new zealand australian rules football gaelic football gridiron football specifically american football arena football canadian football international rules football rugby league football rugby union football various forms football share varying degrees common origins known football codes number references traditional ancient prehistoric ball games played many different parts world contemporary codes football traced back codification games english public schools century outgrowth medieval football expansion cultural power british empire allowed rules football spread areas british influence outside directly controlled empire end century distinct regional codes already developing gaelic football example delib

In [8]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import tensorflow as tf

In [9]:
tokenizer = Tokenizer()

tokenizer.fit_on_texts(clean_doc)
total_words = len(tokenizer.word_index) + 1

In [10]:
print(total_words)


575


In [11]:
input_sequences = []
for line in clean_doc:
  token_list = tokenizer.texts_to_sequences([line])[0]
  for i in range(1, len(token_list)):
    sequence = token_list[:i+1]
    input_sequences.append(sequence)
print(input_sequences)

[[1, 173], [1, 173, 17], [1, 173, 17, 9], [1, 173, 17, 9, 174], [1, 173, 17, 9, 174, 88], [1, 173, 17, 9, 174, 88, 89], [1, 173, 17, 9, 174, 88, 89, 40], [1, 173, 17, 9, 174, 88, 89, 40, 6], [1, 173, 17, 9, 174, 88, 89, 40, 6, 90], [1, 173, 17, 9, 174, 88, 89, 40, 6, 90, 41], [1, 173, 17, 9, 174, 88, 89, 40, 6, 90, 41, 175], [1, 173, 17, 9, 174, 88, 89, 40, 6, 90, 41, 175, 42], [1, 173, 17, 9, 174, 88, 89, 40, 6, 90, 41, 175, 42, 1], [1, 173, 17, 9, 174, 88, 89, 40, 6, 90, 41, 175, 42, 1, 176], [1, 173, 17, 9, 174, 88, 89, 40, 6, 90, 41, 175, 42, 1, 176, 177], [1, 173, 17, 9, 174, 88, 89, 40, 6, 90, 41, 175, 42, 1, 176, 177, 178], [1, 173, 17, 9, 174, 88, 89, 40, 6, 90, 41, 175, 42, 1, 176, 177, 178, 1], [1, 173, 17, 9, 174, 88, 89, 40, 6, 90, 41, 175, 42, 1, 176, 177, 178, 1, 18], [1, 173, 17, 9, 174, 88, 89, 40, 6, 90, 41, 175, 42, 1, 176, 177, 178, 1, 18, 42], [1, 173, 17, 9, 174, 88, 89, 40, 6, 90, 41, 175, 42, 1, 176, 177, 178, 1, 18, 42, 179], [1, 173, 17, 9, 174, 88, 89, 40, 6, 

In [12]:
max_sequence_len = max([len(i) for i in input_sequences])


In [13]:
input_sequences = pad_sequences(input_sequences, maxlen=max_sequence_len, padding="pre")
print(input_sequences)

[[  0   0   0 ...   0   1 173]
 [  0   0   0 ...   1 173  17]
 [  0   0   0 ... 173  17   9]
 ...
 [  0   0   0 ... 170  60 574]
 [  0   0   0 ...  60 574  60]
 [  0   0   0 ... 574  60 155]]


In [15]:
xs = input_sequences[:,:-1]
labels = input_sequences[:,-1]

In [16]:
ys = tf.keras.utils.to_categorical(labels, num_classes=total_words)


In [43]:

embedding_dim=100

model = Sequential()
model.add(Embedding(total_words, embedding_dim, input_length=max_sequence_len-1))
model.add(SimpleRNN(50, return_sequences=True))
model.add(SimpleRNN(50, return_sequences=True))
model.add(SimpleRNN(50, return_sequences=True))

model.add(SimpleRNN(50))
model.add(Dense(total_words, activation='softmax'))

# Compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model.fit(xs, ys, epochs=80, verbose=1)


Epoch 1/80
36/36 [==============================] - 14s 298ms/step - loss: 6.3215 - accuracy: 0.0410
Epoch 2/80
36/36 [==============================] - 11s 305ms/step - loss: 6.0635 - accuracy: 0.0633
Epoch 3/80
36/36 [==============================] - 11s 302ms/step - loss: 5.9292 - accuracy: 0.0633
Epoch 4/80
36/36 [==============================] - 11s 294ms/step - loss: 5.8161 - accuracy: 0.0633
Epoch 5/80
36/36 [==============================] - 11s 302ms/step - loss: 5.6671 - accuracy: 0.0660
Epoch 6/80
36/36 [==============================] - 10s 287ms/step - loss: 5.4978 - accuracy: 0.0723
Epoch 7/80
36/36 [==============================] - 10s 288ms/step - loss: 5.3739 - accuracy: 0.0794
Epoch 8/80
36/36 [==============================] - 11s 301ms/step - loss: 5.2009 - accuracy: 0.1008
Epoch 9/80
36/36 [==============================] - 11s 304ms/step - loss: 5.0212 - accuracy: 0.1222
Epoch 10/80
36/36 [==============================] - 10s 288ms/step - loss: 4.8401 - accura

In [44]:
def generate_next_word(seed_text, next_words):
    for _ in range(next_words):
        token_list = tokenizer.texts_to_sequences([seed_text])[0]
        token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
        predicted_probs = model.predict(token_list)[0]
        predicted_index = np.argmax(predicted_probs)
        output_word = ''
        for word, index in tokenizer.word_index.items():
            if index == predicted_index:
                output_word = word
                break
        seed_text += " " + output_word
    return seed_text

In [47]:

seed_text = "I love"
next_words = 2
generated_text = generate_next_word(seed_text, next_words)
print(generated_text)

1/1 [==============================] - 0s 48ms/step
I love football family


In [49]:

seed_text = "football "
next_words = 3
generated_text = generate_next_word(seed_text, next_words)
print(generated_text)

1/1 [==============================] - 0s 49ms/step
football  family team sports


In [53]:

seed_text = "football league"
next_words = 10
generated_text = generate_next_word(seed_text, next_words)
print(generated_text)

1/1 [==============================] - 0s 48ms/step
football league gridiron football league football college football states game canada football
